/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package moe.sdl.parsemail

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }
}

fun main() {
  println(App().greeting)
}
